import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Search } from 'lucide-react';
import './globals.css';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={`${inter.variable} h-full antialiased`}>
      <body className='min-h-full flex flex-col'>
        <header className='fixed top-0 left-0 right-0 z-50 border-b-1 border-outline bg-background'>
          <div className='grid md:grid md:grid-cols-[4rem_auto_20rem] items-center justify-stretch py-4 px-4 md:h-16 gap-x-2 gap-y-2'>
            <div>
              <img
                src='/bitbid-logo.png'
                alt='BitBid Logo'
                className='w-20 h-10'
              />
            </div>

            <div className='col-span-3 row-start-2 md:col-auto md:row-auto md:mx-2.5'>
              <div className='relative flex items-center'>
                <div className='absolute right-2 text-white'>
                  <Search size={18} strokeWidth={2} />
                </div>
                <input
                  type='text'
                  placeholder='Search for anything'
                  className='w-full h-8.5 bg-foreground text-s text-white placeholder-text-grey border-1 border-outline rounded-sm pl-4 focus:border-white focus:outline-none focus:ring-0 focus-visible:outline-none focus-visible:ring-0'
                />
              </div>
            </div>

            <div className='flex max-md:col-span-2 items-center max-md:justify-end md:justify-around'>
              <div>
                <button className='h-8.5 w-20 rounded-sm hover:bg-foreground'>
                  Sign up
                </button>
              </div>
              <div>
                <button className='h-8.5 w-20 rounded-sm hover:bg-foreground'>
                  Log in
                </button>
              </div>
              <div>
                <button className='bg-brand h-8.5 w-20 ml-2 rounded-sm hover:bg-brand-hover'>
                  Sell
                </button>
              </div>
            </div>
          </div>
        </header>

        {children}

        <footer className='bg-foreground'>
          <div className='mx-auto w-full max-w-screen-xl'>
            <div className='grid grid-cols-2 gap-8 px-4 py-6 lg:py-8 md:grid-cols-4'>
              <div>
                <h2 className='mb-6 text-sm font-semibold text-heading'>
                  ABOUT BitBid
                </h2>
                <ul className='text-body font-medium'>
                  <li className='mb-4'>
                    <a href='#' className=' hover:underline'>
                      Auctions
                    </a>
                  </li>
                  <li className='mb-4'>
                    <a href='#' className='hover:underline'>
                      How Bidding Works
                    </a>
                  </li>
                  <li className='mb-4'>
                    <a href='#' className='hover:underline'>
                      How to Sell
                    </a>
                  </li>
                  <li className='mb-4'>
                    <a href='#' className='hover:underline'>
                      Pricing / Fees
                    </a>
                  </li>
                </ul>
              </div>
              <div>
                <h2 className='mb-6 text-sm font-semibold text-heading uppercase'>
                  Account & Support
                </h2>
                <ul className='text-body font-medium'>
                  <li className='mb-4'>
                    <a href='#' className='hover:underline'>
                      Login / Sign up
                    </a>
                  </li>
                  <li className='mb-4'>
                    <a href='#' className='hover:underline'>
                      Help Center
                    </a>
                  </li>
                  <li className='mb-4'>
                    <a href='#' className='hover:underline'>
                      Contact Support
                    </a>
                  </li>
                  <li className='mb-4'>
                    <a href='#' className='hover:underline'>
                      Report an Issue
                    </a>
                  </li>
                </ul>
              </div>
              <div>
                <h2 className='mb-6 text-sm font-semibold text-heading uppercase'>
                  Legal
                </h2>
                <ul className='text-body font-medium'>
                  <li className='mb-4'>
                    <a href='#' className='hover:underline'>
                      Terms of Service
                    </a>
                  </li>
                  <li className='mb-4'>
                    <a href='#' className='hover:underline'>
                      Privacy Policy
                    </a>
                  </li>
                  <li className='mb-4'>
                    <a href='#' className='hover:underline'>
                      Cookie Policy
                    </a>
                  </li>
                  <li className='mb-4'>
                    <a href='#' className='hover:underline'>
                      Refund Policy
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
          <div className='px-20 py-8 bg-neutral-secondary-soft md:flex md:items-center md:justify-between border-t-1 border-outline'>
            <span className='text-xs text-grey text-body sm:text-center'>
              © 2026 BitBid, All Rights Reserved.
            </span>
          </div>
        </footer>
      </body>
    </html>
  );
}
